live_config_reload = true

[colors.primary]
background = "0x0f111a"
foreground = "0xa6accd"

[colors.bright]
black = "0xff262b"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xeeffff"
yellow = "0xffcb6b"

[colors.normal]
black = "0x666666"
blue = "0x6e98eb"
cyan = "0x71c6e7"
green = "0xabcf76"
magenta = "0xb480d6"
red = "0xdc6068"
white = "0xeeffff"
yellow = "0xe6b455"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 50

[window.padding]
x = 16
y = 12
